import { initializeAmount } from './initAmount.js';
import { initializeAdmin } from './initAdmin.js';
import { initializeRubicSettings } from './rubicSettings.js';
import { initializePumpingPercentages } from './pumpingPercentages.js';
import { initializePumpingLimits } from './pumpingLimits.js';
import { initializeRubicMode } from './rubicMode.js';
import { initializePumpingMultis } from './pumpingMultis.js';
import { initializeSetting } from './initSetting.js';
import { initDoveSetting } from './initDoveSetting.js';
import { initMiningSetting } from './initMiningSetting.js';
import { initRocketSetting } from './initRocket.js';
import { initializeFishingPercentages } from './fishingPercentages.js';
import { initializeFishingLimits } from './fishingLimits.js';
import { initializeCardGamePercentages } from './cardGamePercentages.js';
import { initializeCardGameLimits } from './cardGameLimits.js';
import { initializeJokerCrashLimits } from './jokerCrashLimits.js';
import { initializeJokerCrashIncreases } from './jokerCrashIncreases.js';
import { initializeJokerCrashCards } from './jokerCrashCards.js';
import { initializeJokerCrashPercentages } from './jokerCrashPercentages.js';
import { initAToZSetting } from './initAtoZSettings.js';
import { initCloudSpreadSetting } from './initCloudSpreadSetting.js';
import { initGravityBot } from './initGravityBot.js';
import { initializeMinesSettings } from './minesSettings.js';
import { initializeAlphaTreeSettings } from './initAlphaTreeSettings.js';
import { initializeCocoRates } from './initCocoRates.js';
import { initCoinSettings } from './initCoinSettings.js';
import { initDoubleBotSettings } from './initDoubleBotSettings.js';
import { initializeTwistSettings } from './initTwistSettings.js';
import { initializeKenoControls } from './kenoContrl.js';
import { initializeKenoLimits } from './kenoLimits.js';
import { initializeClimbSettings } from './initClimbSettings.js';
import { initWheelSettings } from './initWheelSettings.js';
import { initializePlinkoRateSettings } from './initPlinkoRateSettings.js';
import { initializePlinkoBotSettings } from './initPlinkoBotSettings.js';
import { initializeThreeNumbersPercentages } from './threeNumbersPercentages.js';
import { initializeThreeNumbersLimits } from './threeNumbersLimits.js';
import { initializeDiamondSettings } from './initDiamondSettings.js';
import { initializeDiamondViews } from './initDiamondViews.js';
import { initializeTarotViews } from './initTarotViews.js';
import { initializeTarotSettings } from './initTarotSettings.js';
import { initializeSnakesSettings } from './snakeSettings.js';
import { initRangeSettings } from './initRangeSettings.js';
import { initializeCryptoCrashPercentages } from './cryptoCrashPercentages.js';
import { initializeCryptoCrashLimits } from './cryptoCrashLimits.js';
import { initializeHashDiceSettings } from './initHashDiceSettings.js';
import { initializeHashDiceBotSettings } from './initHashDiceBotSettings.js';
import { initTrenballBotSettings } from './initTrenballBotSettings.js';
import { trimHashDiceResultsCollection } from '../services/hashDice/hashDiceResult.service.js';


export const initializeDatabase = async () => {
    console.log('🔄 Initializing database...');

    // Initialize all database collections
    await initializeAmount();
    await initializeAdmin();
    await initializeRubicSettings();
    await initializeRubicMode();
    await initializePumpingPercentages();
    await initializePumpingLimits();
    await initializePumpingMultis();
    await initializeSetting();
    await initDoveSetting();
    await initCoinSettings();
    await initMiningSetting();
    await initRocketSetting();
    await initAToZSetting();
    await initCloudSpreadSetting();
    await initGravityBot();
    await initDoubleBotSettings();
    await initializeMinesSettings();
    await initializeAlphaTreeSettings();
    await initializeTwistSettings();
    await initializePlinkoRateSettings();
    await initializePlinkoBotSettings();
    await initializeHashDiceSettings();
    await initializeHashDiceBotSettings();
    await initTrenballBotSettings();
    await trimHashDiceResultsCollection();
    await initializeClimbSettings();
    await initializeDiamondSettings();
    await initializeDiamondViews();
    await initializeTarotSettings();
    await initializeTarotViews();
    await initializeCocoRates();
    await initializeFishingPercentages();
    await initializeFishingLimits();
    await initializeCardGamePercentages();
    await initializeCardGameLimits();
    await initializeJokerCrashLimits();
    await initializeJokerCrashIncreases();
    await initializeJokerCrashCards();
    await initializeJokerCrashPercentages();
    await initializeKenoControls();
    await initializeKenoLimits();
    await initWheelSettings();
    await initializeThreeNumbersPercentages();
    await initializeThreeNumbersLimits();
    await initializeSnakesSettings();
    await initRangeSettings();
    await initializeCryptoCrashPercentages();
    await initializeCryptoCrashLimits();
    console.log('✅ Database initialization complete');
};
